language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAQZRIRXETD574TZ6N
  secret_access_key:
    secure: Mw5FlNet+w4M3q9M2rm8Rn1ieVjhjO05NV1NU3FvvDl+QTIrehS8i8D7MRA34PEk8HMWGCCOGjK7dAgdQwLVVdZnSj3TGyWzOQlz5p9FTXnNJF6SW+S7GlVhoANhZlnCv16VTxL2yhnalsafjnsegjoqg5fkKD76e/vqKAcV8DIawJwR31gXXUzuYy7D4uFztpKbubzrMyiUPn0M3EKzFNrhTRuYVK29O01Le5Vk9VMiS4/VFxxMYPEkoVCHqrZvG21L/yPRAzhuJiWismnsD1ifKaN8+ycQ93ufhzOBT1ZdPs7i9Q5rA1x77q8EZzX5aazQ5Pa24tI7N+jFokGTB5sWwDGgFd+mETRclAxzlArWLO45HsGbtYAHw26hQ2xdrE77OmvAenPRUHcH3v7tHgzGyP/2O7JwWiFU3NcYodIDnZoWGBlcSkD7bdMXJoCjJO6K+MFOAwV9lKWnMH3+N+zP4luHcFX7OM/qT3NgviMV4BxEaD+csPfo+SPhqLvdH3yAt1nL915xq+VQ8NVWJyi1G4avEQ+1Ry1EVA1dw8++dgdPcODYKv4H3ixyRPpMYZz7+lma5XeCFi2xBW84M4qOsQKgF1uu15ZrewLmwHbfmdbeZtyOhvABhzJFY6e2dEX/N4waP2xpxoGl0X3ATkJ3//1huAS4j0R5bGuUOAc=
  bucket: zeroweb
  region: us-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: "./public"
  on:
    branch: master
