language: node_js

node_js:
  - "12"

script:
  - yarn build

deploy:
  provider: s3
  access_key_id: AKIAQZRIRXETKVMEBGLU
  secret_access_key:
    secure: FV5ykVvvQiLI2TJicRbyn/bZxAn5DWE6IK9amhFXnajU5nIwi3olIO0BnC7NeGsFsqPgeIyN6xA47wsm65Ta8L7fAgZqJp8CwIjcYrBq7GBDcmFEQoxytEWVRNk0pdetmTI/DknpRUqvqSHaTCJQVjdnsa2p8QIE30Ld3ljQj7Y6U9ykcRimS0Q5Vck2stVt7jeb5lVXXk4rxu/wnH+uNnzAUneBl7aom34DLgjIFn5MNHfSvb80Y7kNx7O5W45Vxa9OG1hEFduhpWYRMg8izfrEuyGvZ5aOkJADlsiXRyRklib7Ei+2Qfh7+nggwQn7r9FyXMwCiy/5SIpbQ/XHEKJJ516Yj6UqKw108WSv6yxH1qxOo2IO7s7GKmNUKG/iSOYImbOw/Sysx89gcPMIl+dw3b321Z6WCVskoPSJbqkX6mOIAVnsQfr6bDb44OgfqjoAJJlwdTwApt7U0bXCO5uFAte6UK8f8sKfMSphGTVR7fCjC0Tki/Vtg7RHZBqXcOYzgp10fH+3ZLpA2Pl6zjZtaJ6uFs4d0PGHUUsPF30qijoON+6uOgT0hbte2aJ9oJeMk8FsNfLfdfVwno+HXPxaJbwUmANsrKcCbDK5oqOL0k34rkMEmFoVykltLgynyXqOOq80YRbylXvlbp9jbDpMnWpjz9m2Cp4KcVHJxj0=
  bucket: zeroweb
  region: us-west-2
  acl: public_read
  local_dir: public

after_deploy:
  - aws configure set preview.cloudfront true
  - aws cloudfront create-invalidation --distribution