language: node_js
node_js:
- stable
cache:
  directories:
  - node_modules
script:
- yarn build
deploy:
  provider: s3
  access_key_id: AKIAQZRIRXETD574TZ6N
  secret_access_key:
    secure: Mq0AzFkGISG4D7EcTG/dkC6OwCJX07NbBbTl6+HQhaphH+8IFcUq9pmfmiqtHPntHusxDQKMjPDKdp3NRpDqhLDLPCzS6wvKyb1AK3pBrP66tm/xmROujIyay11fTXWeGwMSo25FF3HD82H5DI0fc7PveojRH9K7U09qvkwa5iryN/N7i9iBb9/g85UMC2LrgHbAbytNq/5diXdXVZ0NN7pVIklQI+/Jhk0+6Si9CBxBSFDjhaXErBpbihXFLj3MF0QuzQT0+g99k4g0FNfki9+DkuO79RsHfBBNkVkMXGywDJmfqFCwn69ot/zGZiry9pJfy6mD+qD0fB226pbuJi5jazamySK48mW4gMyAjn5SarpSHEKQUKB9usJjhuhcx0lZk0rke7OZTXNwtKJY0cdrhwBh6EqTpnfNOcR/FVNdHDXTz0uDedLCIpg+t/6/Acfqr1qlbHe8MrpVwvUlcIvKCYY/zrl0ceAJt+iCfiM8hzAEcvJUNZG4tDeZOSXe8TwRdtpW3TO/ZxQGSmJvCsKh/I9NaE9MdsdWHpEoITjLKoC4Fo0WUBVof2K+X61PVyLpLF6biwbgbPeiyV9g6/QzMuwZNdCvYWOixfU4ENKvHsJSc3TgCHkRynOTvxltWYVuS33oeUsh2CvUUuD2glnFUxZqCxMOvPaFVsS2DkI=
  bucket: zeroweb
  region: us-west-2
  acl: public_read
  skip_cleanup: true
  local_dir: public
  on:
    branch: master
