AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Resources:
    ApiGateway:
      Type: "AWS::Serverless::Api"
      Properties:
        Name: "zeroweb-api"
        StageName: "zeroweb-api"
    ApiLambda:
        Type: AWS::Serverless::Function
        Properties:
          FunctionName: zeroweb-api
          Handler: graphql.handler
          Runtime: nodejs14.x
          CodeUri: ./server
          Policies:
            - AmazonDynamoDBFullAccess
          Events:
            AnyRequest:
              Type: Api
              Properties:
                Path: /graphql
                Method: any
                RestApiId: 
                  Ref: ApiGateway
    AuthLambda:
        Type: AWS::Serverless::Function
        Properties:
          FunctionName: zeroweb-auth
          Handler: app.handler
          Runtime: nodejs14.x
          CodeUri: ./auth-server
          Events:
            TwitterLogin:
              Type: Api
              Properties:
                Path: /twitter
                Method: get
                RestApiId: 
                  Ref: ApiGateway
            TwitterCallback:
              Type: Api
              Properties:
                Path: /twitter/callback
                Method: get
                RestApiId:
                  Ref: ApiGateway